websayan/apps/web/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.Index.as_view(), name = 'index'),
    url(r'^comunidad/', views.LaComunidad.as_view(), name = 'comunidad'),
    url(r'^junta-directiva/', views.Junta.as_view(), name = 'junta'),
    url(r'^contacto/', views.Contacto.as_view(), name = 'contacto'),
    url(r'^desarrollo/', views.Desarrollo.as_view(), name = 'desarrollo'),
]

websayan/websayan/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
#from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.web.urls', namespace = 'web')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

"""if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT,}),
]"""

websayan/apps/usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Usuario(AbstractUser):
    avatar = models.ImageField('Foto de perfil', upload_to = 'avatar')

    class Meta:
        ordering = ('username',)
        verbose_name_plural = 'usuarios'

    def __str__(self):
        return self.username

websayan/apps/web/models.py
from django.db import models

class Comunidad(models.Model):

    titulo = models.CharField('Título', max_length=60)
    cuerpo = models.TextField('Descripción')
    imagen = models.ImageField('Imagen', upload_to = 'comunidad')

    class Meta:
        ordering = ['titulo']
        verbose_name_plural = 'La Comunidad'

    def __str__(self):
        return self.titulo

class JuntaDirectiva(models.Model):

    periodo = models.CharField('Periodo', max_length=60)
    nombre = models.CharField('Nombre', max_length=60)
    cargo = models.CharField('Cargo de la persona', max_length=60)
    foto = models.ImageField('Fotografía', upload_to = 'directiva')

    class Meta:
        ordering  = ['-id']
        verbose_name_plural = 'Junta Directiva'

    def __str__(self):
        return self.nombre

class GestionAnterior(models.Model):

    cuerpo = models.TextField('Gestiones')

    class Meta:
        verbose_name_plural = 'Gestión Anterior'

    def __str__(self):
        return self.cuerpo

class Desarrollo(models.Model):

    titulo = models.CharField('Título', max_length=60)
    cuerpo = models.TextField('Descripción')
    imagen = models.ImageField('Imagen', upload_to= 'desarrollo')

    class Meta:
        ordering = ['titulo']
        verbose_name_plural = 'Desarrollo'

    def __str__(self):
        return self.titulo

websayan/apps/web/forms.py
from django import forms

class ContactoForm(forms.Form):

    nombre = forms.CharField(label='Nombre', max_length=60,widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Ingresa tu nombre'}))
    telefono = forms.CharField(label='Teléfono', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Ingresa tu teléfono'}))
    email = forms.EmailField(label='Correo electrónico', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Ingresa tu email', 'type':'email'}))
    mensaje = forms.CharField(label='Mensaje', widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder':'Ingresa tu mensaje'}))

websayan/apps/usuarios/views.py
from django.shortcuts import render

# Create your views here.

websayan/apps/web/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.views.generic import TemplateView
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from .models import JuntaDirectiva, Comunidad, GestionAnterior
from .forms import ContactoForm

class Index(TemplateView):

    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super(Index, self).get_context_data(**kwargs)
        context['juntas'] = JuntaDirectiva.objects.all()
        return context

class LaComunidad(TemplateView):

    template_name = 'comunidad.html'

    def get_context_data(self, **kwargs):
        context = super(LaComunidad, self).get_context_data(**kwargs)
        context['comu'] = Comunidad.objects.all()
        return context

class Junta(TemplateView):

    template_name = 'junta.html'

    def get_context_data(self, **kwargs):
        context = super(Junta, self).get_context_data(**kwargs)
        context['junta'] = JuntaDirectiva.objects.all()
        context['gestion'] = GestionAnterior.objects.all()
        return context

class Contacto(TemplateView):

    template_name = 'contacto.html'

    def get_context_data(self, **kwargs):
        context = super(Contacto, self).get_context_data(**kwargs)
        context['contacto'] = ContactoForm()
        return context

    def post(self, request, *args, **kwargs):
        nombre = request.POST.get('nombre')
        telefono = request.POST.get('telefono')
        email = request.POST.get('email')
        mensaje = request.POST.get('mensaje')

        body= render_to_string(
            'contenido_email.html', {
                'nombre': nombre,
                'telefono': telefono,
                'email': email,
                'mensaje': mensaje,
            },
        )

        mensaje_email = EmailMessage(
            subject = 'Mensaje de Usuario',
            body = body,
            from_email = email,
            to = ['eparionad@gmail.com'],
        )

        mensaje_email.content_subtype = 'html'
        mensaje_email.send()

        return redirect('web:index')

class Desarrollo(TemplateView):

    template_name = 'desarrollo.html'

websayan/apps/web/templates/comunidad.html
{% extends "base.html" %}
{% block title %}La Comunidad{% endblock title %}

{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" type='text/css' href="{% static 'css/sayan.css' %}">
    <link rel="stylesheet" type='text/css' href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type='text/css' href="{% static 'css/fontawesome-all.min.css' %}">
{% endblock css %}

{% block content %}
    <div class="titulos">
        <h1>La Comunidad</h1>
    </div>
    <div class="container-fluid div-comunidad">
        <div class="row">
            <div class="col-12 col-xl-12">
                <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
                {% for comu1 in comu %}
                    <li class="nav-item">
                        <a class="nav-link link-comunidad" id="pills-{{comu1.titulo}}-tab" data-toggle="pill" href="#pills-{{comu1.titulo}}" role="tab" aria-controls="pills-{{comu1.titulo}}" aria-selected="true">{{comu1.titulo}}</a>
                    </li>
                {% endfor %}
                </ul>
                <div class="tab-content" id="pills-tabContent">
                {% for comu2 in comu %}
                    <div class="tab-pane fade show" id="pills-{{comu2.titulo}}" role="tabpanel" aria-labelledby="pills-{{comu2.titulo}}-tab">
                        <div class="row">
                            <div class="col-12 col-sm-12 col-xl-6">
                                <p>{{comu2.cuerpo}}</p>
                            </div>
                            <div class="col-12 col-sm-12 col-xl-6 imagen-comunidad">
                                <img src="{{comu2.imagen.url}}" alt="">
                            </div>
                        </div>
                    </div>
                {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block js %}
    <script src="{% static '/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static '/js/bootstrap.min.js' %}"></script>

{% endblock js %}

websayan/apps/web/templates/contacto.html
{% extends "base.html" %}
{% block title %}Contacto{% endblock title %}

{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" type='text/css' href="{% static 'css/sayan.css' %}">
    <link rel="stylesheet" type='text/css' href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type='text/css' href="{% static 'css/fontawesome-all.min.css' %}">
{% endblock css %}

{% block content %}
    <div class="titulos">
        <h1>Contacto</h1>
    </div>
    <div class="container-fluid div-comunidad">
        <div class="row">
            <div class="col-xl-5 formulario-contacto">
                <form action="" method="post">{% csrf_token %}
                    <div class="form-group row">
                        <label for="Nombre" class="col-xl-2 col-form-label">{{ contacto.nombre.label }}</label>
                        <div class="col-xl-10">
                            {{ contacto.nombre }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="telefono" class="col-xl-2 col-form-label">{{ contacto.telefono.label }}</label>
                        <div class="col-xl-10">
                            {{ contacto.telefono }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="email" class="col-xl-2 col-form-label">{{ contacto.email.label }}</label>
                        <div class="col-xl-10">
                            {{ contacto.email }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="mensaje" class="col-xl-2 col-form-label">{{ contacto.mensaje.label }}</label>
                        <div class="col-xl-10">
                            {{ contacto.mensaje }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-xl-10">
                            <button type="submit" class="btn btn-primary">Enviar</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-xl-7 imagen-comunidad">
                <img src="/media/sayan.jpg" alt="">
            </div>
        </div>
    </div>
{% endblock content %}

{% block js %}
    <script src="{% static '/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static '/js/bootstrap.min.js' %}"></script>

{% endblock js %}

websayan/apps/web/templates/contenido_email.html
<h1 style="font-size:1.5rem; line-height: 2rem;">Mensaje de Usuario</h1>
<p>Udted ha recibo un nuevo mensaje de un usuario</p>

<dl>
    <dt>Nombre</dt>
    <dd>{{ nombre }}</dd>
    <dt>Teléfono</dt>
    <dd>{{ telefono }}</dd>
    <dt>Correo Electrónico</dt>
    <dd>{{ email }}</dd>
    <dt>Mensaje</dt>
    <dd>{{ mensaje }}</dd>
</dl>

websayan/apps/web/templates/desarrollo.html
{% extends "base.html" %}
{% block title %}Desarrollo{% endblock title %}

{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" type='text/css' href="{% static 'css/sayan.css' %}">
    <link rel="stylesheet" type='text/css' href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type='text/css' href="{% static 'css/fontawesome-all.min.css' %}">
{% endblock css %}

{% block content %}
    <div class="titulos">
        <h1>Desarrollo</h1>
    </div>
    <div class="container-fluid div-comunidad">
        <p class="desarrollo">La Comunidad Campesina de Sayán viene ejecutando en cada gestión varios proyectos de desarrollo en beneficio de las actividades económicas de la población.</p>
        <div id="carouselExampleFade" class="carousel slide carousel-fade carrusel-sayan" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item desarrollo-fondo active">
                    <div class="row">
                        <div class="col-xl-6">
                            <img class="d-block w-100" src="/static/media/desarrollo/irrigacion.jpg" alt="First slide">
                        </div>
                        <div class="col-xl-6">
                            <div class="container-fluid">
                                <div class="row texto-carrusel">
                                    <div>
                                        <h3>Irrigación de Sayán</h3>
                                    </div>
                                    <p>Este proyecto consiste en la construcción de un canal de regadío para los agricultores de la Comunidad Campesina de Sayán. La obra conecta la irrigación de Santa Rosa hasta el sector de Río Seco a través de un canal de 20.45 km de largo. Se estima que los trabajos finalizarán en enero del 2019 y beneficiará a 200 comuneros y 145 parcelas agrícolas.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item desarrollo-fondo">
                    <div class="row">
                        <div class="col-xl-6">
                            <img class="d-block w-100" src="/static/media/desarrollo/bus.jpg" alt="First slide">
                        </div>
                        <div class="col-xl-6">
                            <div class="container-fluid">
                                <div class="row texto-carrusel">
                                    <div>
                                        <h3>Bus escolar</h3>
                                    </div>
                                    <p>En el año 2013, la Comunidad Campesina de Sayán adquirió un bus para el transporte de escolares, profesores y padres de familia que asisten a la Institución Educativa N° 345 - Sayán, que se ubica dentro de la comunidad. De esta forma se garantiza que los niños y niñas acudan sus clases y no se perjudique la educación de los menores de Sayán.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="carousel-item desarrollo-fondo">
                    <div class="row">
                        <div class="col-xl-6">
                            <img class="d-block w-100" src="/static/media/desarrollo/irrigacion.jpg" alt="First slide">
                        </div>
                        <div class="col-xl-6">
                            <div class="container-fluid">
                                <div class="row texto-carrusel">
                                    <div>
                                        <h3>Capacitación agrícola</h3>
                                    </div>
                                    <p>Desde el año 2018, la comunidad implementará talleres de capacitación agrícola para los comuneros de Sayán. El objetivo es impulsar la actividad agrícola con asistencia técnica e inserción al mercado local y exportador.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev control" href="#carouselExampleFade" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon icono-carrusel" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next control" href="#carouselExampleFade" role="button" data-slide="next">
                <span class="carousel-control-next-icon icono-carrusel" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
{% endblock content %}

{% block js %}
    <script src="{% static '/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static '/js/bootstrap.min.js' %}"></script>

{% endblock js %}

websayan/apps/web/templates/index.html
{% extends "base.html" %}
{% block title %}Inicio{% endblock title %}

{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" type='text/css' href="{% static 'css/sayan.css' %}">
    <link rel="stylesheet" type='text/css' href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type='text/css' href="{% static 'css/fontawesome-all.min.css' %}">
{% endblock css %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 centrar-texto">
                <h1>!Sayán, comunidad próspera y con visión de futuro¡</h1>
            </div>
            <div class="col-sm-12 imagen-index">
                <img src="/static/media/sayan.jpg">
            </div>
        </div>
    </div>
    
{% endblock content %}

{% block js %}
    <script src="{% static '/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static '/js/bootstrap.min.js' %}"></script>
{% endblock js %}

websayan/apps/web/templates/junta.html
{% extends "base.html" %}
{% block title %}Junta Directiva{% endblock title %}

{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" type='text/css' href="{% static 'css/sayan.css' %}">
    <link rel="stylesheet" type='text/css' href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type='text/css' href="{% static 'css/fontawesome-all.min.css' %}">
{% endblock css %}

{% block content %}
    <div class="titulos">
        <h1>Junta Directiva</h1>
    </div>
    <div class="container-fluid div-comunidad">
        <div class="row">
            <div class="col-xl-12">
                <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active link-comunidad" id="pills-juntadirectiva-tab" data-toggle="pill" href="#pills-juntadirectiva" role="tab" aria-controls="pills-juntadirectiva" aria-selected="true">Periodo 2017 -2018</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link link-comunidad" id="pills-gestionanterior-tab" data-toggle="pill" href="#pills-gestionanterior" role="tab" aria-controls="pills-gestionanterior" aria-selected="true">Gestion Anterior</a>
                    </li>
                </ul>
                <div class="tab-content" id="pills-tabContent">
                    <div class="tab-pane fade show active" id="pills-juntadirectiva" role="tabpanel" aria-labelledby="pills-juntadirectiva-tab">
                        <div class="row junta-directiva order-first">
                            {% for junta2017 in junta %}
                                <div class="card-deck col-xl-3 perfil">
                                    <div class="card">
                                        <img class="card-img-top" src="{{ junta2017.foto.url }}" alt="">
                                        <div class="card-body">
                                            <h5 class="card-title">{{ junta2017.nombre }}</h5>
                                            <p class="card-text">{{ junta2017.cargo }}</p>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="tab-pane fade show" id="pills-gestionanterior" role="tabpanel" aria-labelledby="pills-gestionanterior-tab">
                        <div class="row junta-directiva">
                            <div>
                                {% for gestionant in gestion %}
                                    <p>{{ gestionant.cuerpo | linebreaks }}</p>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block js %}
    <script src="{% static '/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static '/js/bootstrap.min.js' %}"></script>

{% endblock js %}

websayan/templates/base.html
<!DOCTYPE html>
<html lang="es-PE">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock title %} </title>
    {% block css %}{% endblock css %}
</head>
<body>
    <div class="container-fluid">
        <div class="row inicio">
            <div class="col-12 col-sm-3 col-xl-1 logo">
                <img src="/static/media/logos/logo.png" alt="Logo Comunidad Sayán">
            </div>
            <div class="align-self-center col-12 col-sm-9 col-xl-5">
                <div class="row justify-content-center nombre-comunidad">
                    <h1>COMUNIDAD CAMPESINA DE SAYÁN</h1>
                    <h6>Reconocida por Resolución Suprema del 17 de junio de 1942</h6>
                </div>
            </div>
            <div class="align-self-center col-12 col-sm-12 col-xl-6">
                <div class="menu-responsive">
                    <nav class="navbar navbar-dark navbar-expand-lg menu">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#menusayan" aria-controls="menusayan" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="menusayan">
                            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                                <li class="nav-item">
                                    <a class="enlaces" href="{% url 'web:index' %}">Inicio</a>
                                </li>
                                <li>
                                    <a class="enlaces" href="{% url 'web:comunidad' %}">La Comunidad</a>
                                </li>
                                <li>
                                    <a class="enlaces" href="{% url 'web:desarrollo' %}">Desarrollo</a>
                                </li>
                                <li>
                                    <a class="enlaces" href="{% url 'web:junta' %}">Junta Directiva</a>
                                </li>
                                <li>
                                    <a class="enlaces" href="{% url 'web:contacto' %}">Contacto</a>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    {% block content %}{% endblock content %}
    <div class="container-fluid footer">
        <footer class="row pie">
            <div class="col-12 col-sm-12 col-xl-4 sociales">
                <a href="http://www.google.com.pe" target="_blank"><i class="fab fa-facebook-square fa-2x"></i></a>
                <a href="http://www.google.com.pe" target="_blank"><i class="fab fa-instagram fa-2x"></i></a>
                <a href="http://www.google.com.pe" target="_blank"><i class="fab fa-youtube fa-2x"></i></a>
            </div>
            <div class="col-12 col-sm-12 col-xl-8">
                <div class="row texto-footer">
                    <p class="h6">Carretera Río Seco Km.20 - Sector El Ahorcado</p>
                </div>
                <div class="row texto-footer1">
                    <p class="h6">Distrito de Sayán - Huaura - Lima</p>
                </div>
            </div>
        </footer>
    </div>
    {% block js %}{% endblock js %}
</body>
</html>